# This file contains the default configuration settings for Pyramis. You can override these settings by creating a `config.toml` file in the same directory as your script or notebook, and specifying the desired settings there.
# Except for directory paths, changing the file name formats are not recommended.

## Verbosity level for logging. Higher values will produce more detailed logs.
VERBOSE_LEVEL = 1

## Directory paths for input and output data. You can change these to match your directory structure.
OUTPUT_FORMAT = "output_{iout:05d}"
OUTPUT_FORMAT_ANY = "output_*"

FILENAME_FORMAT_RAMSES = "{data}_{iout:05d}.out{icpu:05d}"
FILENAME_FORMAT_RAMSES_ANY = "{data}_{iout:05d}.out*"

NAMELIST_FILENAME = "namelist.txt"
FILE_DESCRIPTOR_FORMAT = "{data}_file_descriptor.txt"

FILENAME_FORMAT_HDF = "hdf/{data}_{iout:05d}.h5"
FILENAME_FORMAT_HDF_ANY = "hdf/{data}_*.h5"

FILENAME_FORMAT_HALOMAKER = "halo/tree_bricks{iout:05d}"
FILENAME_FORMAT_GALAXYMAKER = "galaxy/tree_bricks{iout:05d}"
FILENAME_FORMAT_PTREE = "ptree/ptree_{iout:05d}.pkl"

## Default variable name set to use when reading data. "native" and "simple" are possible.
VNAME_SET = "native"

FILENAME_FORMAT_SINKPROPS_ANY = "SINKPROPS/sink_*.dat"
FILENAME_FORMAT_SINKPROPS = "SINKPROPS/sink_{icoarse:05d}.dat"

FILENAME_FORMAT_DYABLO = "{prefix}_iter{istep:07d}.h5"

## Default settings for reading RAMSES output.
### Number of processes to use for parallel processing. "auto" will use all available CPU cores.
DEFAULT_N_PROCS = "auto"
### Number of subdivisions for the domain computation for RAMSES output, higher values will increase accuracy but also increase computation time.
DEFAULT_LEVEL_SUBDIVIDE = 2

## Data type definitions for reading sink particle properties. This should match the structure of the sink property files generated by RAMSES.
SINKPROPS_DTYPE = [
    ["identity", "i4"], ["mass", "f8"],
    ["position_x", "f8"], ["position_y", "f8"], ["position_z", "f8"],
    ["velocity_x", "f8"], ["velocity_y", "f8"], ["velocity_z", "f8"],
    ["jsink_x", "f8"], ["jsink_y", "f8"], ["jsink_z", "f8"],
    ["birth_time", "f8"], ["dMBHoverdt", "f8"], ["dMEdoverdt", "f8"], ["dMsmbh", "f8"],
    ["d_avgptr", "f8"], ["c_avgptr", "f8"], ["v_avgptr", "f8"],
    ["Esave", "f8"], ["spin_x", "f8"], ["spin_y", "f8"], ["spin_z", "f8"],
    ["spin_magnitude", "f8"], ["eps_sink", "f8"],
    ["rho_star", "f8"], ["rho_dm", "f8"],
    ["star_vx", "f8"], ["star_vy", "f8"], ["star_vz", "f8"],
    ["dm_vx", "f8"], ["dm_vy", "f8"], ["dm_vz", "f8"],
    ["n_star", "i4"], ["n_dm", "i4"],
    ["rho_star_slow", "f8"], ["rho_dm_slow", "f8"],
    ["f_star_fast", "f8"], ["f_dm_fast", "f8"],
    ["DF_gas", "f8"], ["DF_star", "f8"], ["DF_dm", "f8"],
]

## Variable name mapping for different naming conventions. You can add your own naming convention by adding a new section here and filling in the appropriate mappings.
[VNAME_MAPPING.simple]
position_x = "x"
position_y = "y"
position_z = "z"
velocity_x = "vx"
velocity_y = "vy"
velocity_z = "vz"
mass = "m"
identity = "id"
density = "rho"
pressure = "P"
metallicity = "metal"
initial_mass = "m0"
birth_time = "epoch"
birth_density = "rho0"
chem_H = "H"
chem_O = "O"
chem_Fe = "Fe"
chem_Mg = "Mg"
chem_C = "C"
chem_N = "N"
chem_Si = "Si"
chem_S = "S"
chem_D = "D"
dust_bin01 = "d1"
dust_bin02 = "d2"
dust_bin03 = "d3"
dust_bin04 = "d4"
refinement_scalar = "refmask"
dMsmbh = "dM"
dMBH_coarse = "dMBH"
dMEd_coarse = "dMEd"
jsink_x = "jx"
jsink_y = "jy"
jsink_z = "jz"
spin_x = "sx"
spin_y = "sy"
spin_z = "sz"
spin_magnitude = "spinmag"
potential = "phi"
num_parts = "nparts"
timestep = "iout"
hosthalo = "host"
angular_momentum_x = "Lx"
angular_momentum_y = "Ly"
angular_momentum_z = "Lz"
virial_radius = "rvir"
virial_mass = "mvir"
virial_temperature = "tvir"
circular_velocity = "vcir"
density_0 = "rho0"
radius_c = "rc"
radius = "r"
semi_axis_a = "a"
semi_axis_b = "b"
semi_axis_c = "c"
kinetic_energy = "ekin"
potential_energy = "epot"
total_energy = "etot"
spin_parameter = "spin"
mass_bulge = "mbulge"

DIM_KEYS = ["x", "y", "z"]

[VNAME_MAPPING.native]

DIM_KEYS = ["position_x", "position_y", "position_z"]


## Unit definitions for converting between different unit systems.
[CGS_UNIT]
km = 1e5
pc = 3.08e18
kpc = 3.08e21
Mpc = 3.08e24
Gpc = 3.08e27
yr = 3.1536e7
Myr = 3.1536e13
Gyr = 3.1536e16

K = 1.0
Msun = 2e33

## Physical constants in CGS units.
[CGS_CONSTANTS]
m_u = 1.66e-24
k_B = 1.38e-16

## Particle type definitions that can be converted to particle family in RAMSES output. Multiple families can be assigned to the same type.
[PARTICLE_TYPE_DEFINITION]
cloud_tracer = -3
star_tracer = -2
gas_tracer = 0
dm = 1
star = 2
cloud = 3
tracer = [-3, -2, 0]
init = [-3, -2, 0, 1]